### ISSUE TITLE
Not working > 0.15.0

### ISSUE THREAD

**Issue by FilleDev** [MCFT-Server/FloatingText#1]
Hello!

The plugin is not working for 0.15.0 Nukkit. I can't see the text. Can you fix it? @wsj7178 

Best Regards,
File14

**Comment by FilleDev** [comment]
Please @wsj7178

**Comment by wsj7178** [comment]
It maybe 0.15.0 or nukkit's problem.
I'm sorry but I don't know how to fix it. @File14

**Comment by FilleDev** [comment]
https://github.com/Nukkit/Nukkit/blob/0.15.0/src/main/java/cn/nukkit/level/particle/FloatingTextParticle.java

Maybe the text is invisisble? Can you set it visable and maybe that will work.

**Comment by wsj7178** [comment]
In mcpe 0.15.0, Entity ID -1  is removed.
Only mojang(or shoghi) can fix it.

**Comment by File14** [comment]
It is now working in Nukkit 0.15 can you please add color codes support? :) @wsj7178
